---
title: "Prodigy Infotech"
author: "Jassica Michael"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(repos = "https://cloud.r-project.org")

install.packages("ggplot2")  # Install if you haven't yet
install.packages("tidyverse") # For data manipulation
library(ggplot2)
library(tidyverse)

```



```{r}
# Install the readxl package
install.packages("readxl")

# Install the openxlsx package (if you want to write or edit Excel files as well)
install.packages("openxlsx")




```


```{r}
# Load the readxl package
library(readxl)

# Alternatively, you can load openxlsx
# library(openxlsx)

```

```{r}
# Read the Excel file (replace 'path_to_your_file.xlsx' with the actual file path)
data <- "C:/Users/jessica/Desktop/population_dynamics.xlsx"

# View the first few rows of the data
population <-read_excel(data)
head(population)

```


```{r}
install.packages("dplyr")
library(dplyr)

```


```{r}
clean_data<-population[4:nrow(population),c(1,3,6,7,8)]
head(clean_data)
```


```{r}
colnames(clean_data)<-c("Country","Population_2023","Ages_0_14","Ages_15_64","Ages_65_plus") 
head(clean_data)

```

```{r}
clean_data$Population_2023<-as.numeric(clean_data$Population_2023)
clean_data$Ages_0_14<-as.numeric(clean_data$Ages_0_14)
clean_data$Ages_15_64<-as.numeric(clean_data$Ages_15_64)
clean_data$Ages_65_plus<-as.numeric(clean_data$Ages_65_plus)
head(clean_data)

```
```{r}
clean_data<-clean_data[is.finite(clean_data$Population_2023)&is.finite(clean_data$Ages_0_14)&is.finite(clean_data$Ages_15_64)&is.finite(clean_data$Ages_65_plus),]
head(clean_data)
```
```{r}
install.packages("tidyr")
library(tidyr)
```


```{r}
long_data<- pivot_longer(clean_data,cols=c("Ages_0_14","Ages_15_64","Ages_65_plus"),names_to="Age_group",values_to="Age_percentage")
head(long_data)
```
```{r}
ggplot(long_data,aes(x=Age_group,y=Population_2023,fill=Age_group))+geom_bar(stat = "identity",position= "dodge")+labs(title = "Population in 2023 by group",x="Age Group", y="Population(millions)")+theme_minimal()
```


```{r}
library(ggplot2)
ggplot (clean_data,aes(x=Population_2023))+geom_histogram(binwidth=1000,fill="purple",color="black")+labs(title="population distribution in 2023",x="Population(millions)",y="Count")
```

